### ISSUE TITLE
Technical Design and Architecture of IM Services / PACT Directory - MVP

### ISSUE THREAD

**Issue by bhadley** [wbcsd/pact-directory#1]
Creation of Technical Design Documentation for PACT IM MVP:

- Technical Architecture
- System flow diagram (?)
- Authentication service options analysis (OAuth, DNS, etc.), pros/cons and recommendation
- How would the OAuth work? What are the various flows? Bidirectional authentication
- etc

To prepare as a pre-read document for Nov 13 IM Sub-WG

**Comment by jmarmolejos** [comment]
Document: https://github.com/wbcsd/pact-directory/blob/main/docs/authentication-as-a-service-design.md
